# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  push:
    name: Push ${{ github.ref }}
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Fetch depth
        run: echo "FETCH_DEPTH=$(echo '${{ toJSON(github.event.commits) }}' | jq 'length | if . < 20 then . + 1 else 0 end')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Fetch deps
        run: yarn --silent --immutable

      - name: Build
        run: |
          yarn warmup
          yarn build

      - name: Coverage
        run: yarn cov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Codeclimate
        if: github.ref == 'refs/heads/master'
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/lcov.info:lcov

      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: true
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
        run: npm_config_yes=true npx zx-bulk-release --no-build

  pr:
    if: github.event_name == 'pull_request'
    name: PR
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout/issues/552
      - name: Fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Fetch deps
        run: yarn --silent --immutable

      - name: Build
        run: |
          yarn warmup
          yarn build

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: |
            package.json
            packages/**/target/esm/**/*
            packages/**/target/cjs/**/*
            packages/**/target/dts/**/*
            packages/**/target/coverage/lcov.info

  pr-compat:
    needs: pr
    name: Compat test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
        node-version: [ 18, 20 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          # TODO Handle fetch depth for windows
          fetch-depth: 25

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

#      - name: Log
#        run: node -e "console.log('commits=', process.env.COMMITS)"
#        env:
#          COMMITS: ${{ toJSON(github.event.pull_request.commits) }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Fetch deps
        run: yarn --silent --immutable

      - name: Integration test
        run: yarn test --testCmd="yarn test:it"
